version: '3.8'

services:
  bazel-remote:
    image: buchgr/bazel-remote:v2.4.4
    container_name: moon-bazel-remote-cache
    restart: unless-stopped
    ports:
      - '9092:9092' # gRPC
      - '8080:8080' # HTTP
    volumes:
      - bazel-cache-data:/data
    command:
      - '--max_size=10'
      - '--dir=/data'
      - '--grpc_address=0.0.0.0:9092'
      - '--http_address=0.0.0.0:8080'
      - '--storage_mode=zstd'

volumes:
  bazel-cache-data:
